### ISSUE TITLE
Android:Evo-gen[Trj]

### ISSUE THREAD

**Issue by Abhi5h3k** [h-mdm/remote-control-android#13]
Hey,

I just installed the [Headwind Remote](https://play.google.com/store/apps/details?id=com.hmdm.control) app on my device and got **Android:Evo-gen[Trj]**  trojan alert.

> Can anyone confirm, **Is it False Positive**!! 

**Anti-virus** : Bitdefender

<img src="https://user-images.githubusercontent.com/37928721/207299481-5d544d52-fe47-4c77-80c3-13fd33945b6b.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/37928721/207299426-060075b7-d97f-4d5e-841c-071e523843d2.png" width="200" height="400" />

**Comment by h-mdm** [comment]
Any remote control app is potentially unsafe because it enables remote access to your mobile device.

Headwind Remote is open source and its code can be reviewed for potential data leaks. As far as I know, there isn't, so the app from Google Play is safe to use.

So if you want to use it, please add it to allowlist.

**Comment by Abhi5h3k** [comment]
Thank you @h-mdm, I will do that.
Previously I used different remote access app and never got this alert.
